services:
  - type: web
    name: odoo-app
    env: docker
    plan: free
    image: odoo:17
    envVars:
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8069"
      - key: DATABASE_URL
        fromDatabase:
          name: odoo-db
          property: connectionString

databases:
  - name: odoo-db
    plan: free
    databaseName: odoo
    user: odoo
