services:
  - type: web
    name: odoo-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        value: "dpg-d1u06o3e5dus73e2nps0-a"
      - key: PORT
        value: "5432"
      - key: DATABASE_URL
        Value: "postgresql://odoo:zxmlESVjyQee4odDCSds1S1LsQKdJHzk@dpg-d1u06o3e5dus73e2nps0-a/odoo_4crj"
        fromDatabase:
          name: odoo-db
          property: connectionString

databases:
  - name: odoo-db
    plan: free
    databaseName: odoo
    user: odoo
